# Generated by Django 3.0.2 on 2020-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='date_on_market',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
