# Generated by Django 3.0.2 on 2020-01-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20200129_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideeffect',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.Medication'),
        ),
    ]
